### ISSUE TITLE
Short URL creation: ALL keyword 'ABC' converted to 'abc'

### ISSUE THREAD

**Issue by Doncellup** [YOURLS/force-lowercase#5]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Hello,
Currently ONLY custom keywords are lowercased.
It could be nice if ALL keywords were lowercased (I think of random keywords!).

### Motivation

It would make sense to add this feature.
However if you do not want to add it directly to the plugin can you explain to me how I can modify the code of the `plugin.php` so that it works?

**Comment by ozh** [comment]
Simply set [YOURLS_URL_CONVERT](https://docs.yourls.org/guide/essentials/charset.html) to 36 ? If you're using this plugin, it does not make sense to use anything else
